#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge -I ~/.Xresources

setxkbmap es -option "ctrl:nocaps"
xsetroot -cursor_name left_ptr
xset r rate 200 50 &
xcompmgr -c -n &
nm-applet &
dropbox start &
pactl load-module module-bluetooth-discover &
blueman-applet &

if [-n "$WORK_STATION"]; then
    gnome-screensaver &
else 
    xscreensaver -no-splash &
fi

ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
sh ~/.xmonad/wallpaper_switcher &
polybar topbar -c ~/.xmonad/polybar-config.ini &

exec xmonad
