#!/bin/sh
[ -f ~/.Xresources ] && xrdb -merge -I ~/.Xresources

setxkbmap -layout "us(altgr-intl)" -option "ctrl:nocaps"
xsetroot -cursor_name left_ptr
xset r rate 300 50 &

if [ -n "$(command picom)" ]; then
    picom &
elif [ -n "$(command compton)" ]; then
    picom &
fi

nm-applet &
dropbox start &
pactl load-module module-bluetooth-discover &
blueman-applet &
udiskie -a -s &

if [ -n "$(command gnome-screensaver)" ]; then
    gnome-screensaver &
elif [ -n "$(command xscreensaver)" ]; then
    xscreensaver -no-splash &
fi

ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3 &
sh ~/.xmonad/wallpaper_switcher &
polybar topbar -c ~/.xmonad/polybar-config.ini &

exec xmonad
