#!/bin/sh
[ -f ~/.Xresources ] && xrdb -merge -I ~/.Xresources

setxkbmap -layout "us(altgr-intl)" -option "ctrl:nocaps"
xsetroot -cursor_name left_ptr
xset r rate 300 50 &

if [ -n "$(command -v picom)" ]; then
    picom &
elif [ -n "$(command -v compton)" ]; then
    compton &
fi

nm-applet &
dropbox start &
pactl load-module module-bluetooth-discover &
blueman-applet &
udiskie -a -s &
dunst &

if [ -n "$(command -v gnome-screensaver)" ]; then
    gnome-screensaver &
elif [ -n "$(command -v xscreensaver)" ]; then
    xscreensaver -no-splash &
fi

ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3 &
sh ~/.config/xmonad/wallpaper_switcher &

if [ -n "$(command -v gnome-keyring)" ]; then
    eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
    export SSH_AUTH_SOCK
fi

exec xmonad
