resolver: nightly-2020-04-30

packages:
- .

extra-deps:

flags: {}

nix:
  packages:
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXScrnSaver
    - xorg.libXft
    - pkgconfig
